# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f67c554ee90f4ccce56edefe9c06238828ce794ddaaf302560f4b37d5a1b982ce59cd7b869915eb35e84a807a4a2c49e46cd5a19f5244608f7b669b74590d069

test:
  secret_key_base: 3d85f38536363c507131ae1c963fa00ac6263637444c510af0d44ab3b3b4c09e6b01982f5562b880943f93078c6fdc1b018963a233d6bff93f4c7cd82e57a489

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
